INSERT INTO roles(name) VALUES('ROLE_USER');
INSERT INTO roles(name) VALUES('ROLE_TECNICO');
INSERT INTO roles(name) VALUES('ROLE_ADMIN');
INSERT INTO especialidade(descricao) VALUES('Saúde da mulher');
INSERT INTO especialidade(descricao) VALUES('Saúde mental');
INSERT INTO especialidade(descricao) VALUES('Primeiro socorros');
INSERT INTO especialidade(descricao) VALUES('Covid-19');
INSERT INTO especialidade(descricao) VALUES('Saúde do idoso');
INSERT INTO especialidade(descricao) VALUES('Saúde do adulto');
INSERT INTO especialidade(descricao) VALUES('Saúde da criança e adolescente');